common_timezone: 'Etc/UTC'
main_user_shell: "/bin/bash"
sshd_config: /etc/ssh/sshd_config
sshd: ssh

env_groups: "{{ ['development', 'staging', 'production'] | intersect(group_names) }}"
apt_packages_default:
  python-software-properties: "{{ apt_package_state }}"
  python-pycurl: "{{ apt_package_state }}"
  build-essential: "{{ apt_package_state }}"
  python-mysqldb: "{{ apt_package_state }}"
  curl: "{{ apt_package_state }}"
  git: "{{ apt_package_state }}"
  dbus: "{{ apt_package_state }}"
  libnss-myhostname: "{{ apt_package_state }}"
  vim: "{{ apt_package_state }}"
  htop: "{{ apt_package_state }}"
  iftop: "{{ apt_package_state }}"
  iotop: "{{ apt_package_state }}"
  sysstat: "{{ apt_package_state }}"
  unzip: "{{ apt_package_state }}"
  wget: "{{ apt_package_state }}"
  vnstat: "{{ apt_package_state }}"
  ncdu: "{{ apt_package_state }}" # Great tool for disk usage `ncdu -rx /`

apt_packages_custom: {}
apt_packages: "{{ apt_packages_default | combine(apt_packages_custom) }}"

openssh_6_8_plus: "{{ (lookup('pipe', 'ssh -V 2>&1')) | regex_replace('(.*OpenSSH_([\\d\\.]*).*)', '\\2') is version_compare('6.8', '>=') }}"
overlapping_ciphers: "[{% for cipher in (sshd_ciphers_default + sshd_ciphers_extra) if cipher in ssh_client_ciphers %}'{{ cipher }}',{% endfor %}]"
overlapping_kex: "[{% for kex in (sshd_kex_algorithms_default + sshd_kex_algorithms_extra) if kex in ssh_client_kex %}'{{ kex }}',{% endfor %}]"
overlapping_macs: "[{% for mac in (sshd_macs_default + sshd_macs_extra) if mac in ssh_client_macs %}'{{ mac }}',{% endfor %}]"
host_key_types: "[{% for path in sshd_host_keys %}'{{ path | regex_replace('/etc/ssh/ssh_host_(.+)_key', '\\1') | regex_replace('dsa', 'ssh-dss')}}',{% endfor %}]"
overlapping_host_keys: "{% for key in host_key_types if key in ssh_client_host_key_algorithms %}{{ key }},{% endfor %}"