# gitlab backup
gitlab_backup_enable: true
gitlab_backup_aws_region: ap-south-1
gitlab_backup_aws_access_key_id: AKIAIS7ENZH46462D67A
gitlab_backup_aws_secret_access_key: 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
gitlab_backup_aws_bucket: charcoal-gitlab-backup

# gitlab mail
gitlab_smtp_enable: true
gitlab_smtp_address: "smtp.sendgrid.net"
gitlab_smtp_port: 587
gitlab_smtp_user_name: 'apikey'
gitlab_smtp_password: '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'
gitlab_smtp_domain: 'charcoaleats.com'

# gitlab https
gitlab_nginx_listen_https: 443
gitlab_create_self_signed_cert: false
gitlab_tls_src_cert: "/home/cloud9/workspace/charcoal-ansible-scripts/pub_keys/charcoaleats.crt"
gitlab_tls_src_cert_key: "/home/cloud9/workspace/charcoal-ansible-scripts/pub_keys/charcoaleats.key"
gitlab_redirect_http_to_https: "true"
gitlab_ssl_certificate: "/etc/ssl/charcoaleats.crt"
gitlab_ssl_certificate_key: "/etc/ssl/charcoaleats.key"
