---
consul_domain: '{{ prod_consul_domain }}'
consul_datacenter: '{{ prod_consul_datacenter }}'
consul_acl_master_token: "06315bee-1433-4852-bd44-3665b73ea28c"
consul_acl_agent_token: "0c75e0c0-9ffe-4dd6-bd9f-acb02ea2b0d3"

# Monit
monit_mail_enabled: true
monit_mailserver_host: smtp.gmail.com
monit_mailserver_port: 587
monit_mailserver_user: alert@charcoaleats.com
monit_mailserver_password: amit@17031993
monit_mailserver_ssl_version: tlsv1
monit_mailserver_timeout: 30
monit_alert_addresses:
  - developer@charcoaleats.com
monit_alert_mail_from: alert@charcoaleats.com
monit_alert_mail_subject: alert
monit_alert_mail_message: |+
  $EVENT Service $SERVICE
              Date:        $DATE
              Action:      $ACTION
              Host:        $HOST
              Description: $DESCRIPTION
              IP: $ADDRESS
        Your faithful employee,
        Monit

  # - name: nginx
  #   type: process
  #   target: /var/run/nginx.pid
  #   start: /usr/sbin/service nginx start
  #   stop: /usr/sbin/service nginx stop
  #   restart: /usr/sbin/service nginx restart
  #   rules:
  #     - "if failed port 80 protocol http then restart"
  #     - "if 5 restarts within 5 cycles then timeout"