---
consul_domain: '{{ prod_consul_domain }}'
consul_datacenter: '{{ prod_consul_datacenter }}'
consul_acl_master_token: "06315bee-1433-4852-bd44-3665b73ea28c"
consul_acl_agent_token: "0c75e0c0-9ffe-4dd6-bd9f-acb02ea2b0d3"

consul_acl_configuration_list:
  Agent:
    token_type: client
    token: "{{ consul_acl_agent_token }}"
    rules:
      - key: ""
        policy: write
      - node: ""
        policy: write
      - service: ""
        policy: write
  ## ACL for anonymous UI reading
  Anonymous Token:
    token_type: client
    token: anonymous
    rules:
      - key: ""
        policy: read
      - node: ""
        policy: read
      - service: ""
        policy: read


netdata_alert_addresses:
  - developer@charcoaleats.com


# Monit
monit_mail_enabled: true
monit_mailserver_host: smtp.sendgrid.net
monit_mailserver_port: 587
monit_mailserver_user: apikey
monit_mailserver_password: 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
monit_mailserver_ssl_version: tlsv1
monit_mailserver_timeout: 30
monit_alert_addresses:
  - amit@charcoaleats.com
  - developer@charcoaleats.com
monit_alert_mail_from: alert@charcoaleats.com
monit_alert_mail_subject: alert
monit_alert_mail_message: |+
  $EVENT Service $SERVICE
              Date:        $DATE
              Action:      $ACTION
              Host:        $HOST
              Description: $DESCRIPTION
              IP: $ADDRESS
        Your faithful employee,
        Monit
