---
consul_server_nodes: 
  - '{{ consul_server_ip }}'
consul_domain: '{{ prod_consul_domain }}'
consul_datacenter: '{{ prod_consul_datacenter }}'

## ACL for discovery synchronization between servers
consul_acl_configuration_list:
  Agent:
    token_type: client
    token: "{{ consul_acl_agent_token }}"
    rules:
      - node: ""
        policy: write
      - service: ""
        policy: write
  ## ACL for anonymous UI reading
  Anonymous Token:
    token_type: client
    token: anonymous
    rules:
      - key: ""
        policy: read
      - node: ""
        policy: read
      - service: ""
        policy: read