# Documentation: https://roots.io/trellis/docs/ssh-keys/
admin_user: dranzer

users:
  - name: "dranzer" # Ansible User
    groups:
      - sudo
    keys:
      - "{{ lookup('file', '/Users/amitverma/Projects/side-projects/galactus/pub_keys/dranzer.pub') }}"

  - name: "cerberus" # Admin User 
    groups:
      - sudo
    keys:
      - "{{ lookup('file', '/Users/amitverma/Projects/side-projects/galactus/pub_keys/cerberus.pub') }}"

  - name: "scylla" # Deploy User
    groups:
      - www-data
    keys:
      - "{{ lookup('file', '/Users/amitverma/Projects/side-projects/galactus/pub_keys/scylla.pub') }}"
