---
- name: Fetch Projects from git remote host
  git:
    repo: "{{ item.remote_url }}"
    dest: "{{ item.path }}"
    key_file: "/home/{{ ssh_git_user }}/.ssh/id_rsa.key"
  with_items: "{{ git_repos }}"