---
- name: git-deploy | add ssh key
  template:
    src: "id_rsa.key"
    dest: "{{ user_home_path }}/.ssh/id_rsa.key"
    owner: "{{ ssh_git_user }}"
    group: "sudo"
    mode: 0400

- name: git-deploy | Configure ssh to use ansible key
  template:
    src: "ssh_config.j2"
    dest: "{{ user_home_path }}/.ssh/config"
    owner: "{{ ssh_git_user }}"
    group: "sudo"
    mode: 0644

- name: git-deploy |  Ensure apps directory present
  file:
    path: /var/apps
    state: directory
    owner: "{{ ssh_git_user }}"
    group: "{{ deploy_user_group }}"
    mode: 0777

- include_tasks: get-repo.yml  
  when: fetch_repo_from_remote_host
