---
consul_version: 1.2.2

consul_user: consul
consul_group: consul
consul_nodename: '{{ server_name }}'

consul_force_install: false

## List with the hosts acting as servers
# consul_server_nodes: 
consul_basedir: /opt/consul

consul_bindir: "{{ consul_basedir }}/bin"
consul_configdir: "{{ consul_basedir }}/consul.d"
consul_datadir: "{{ consul_basedir }}/data"
consul_syslog: false

consul_logdir: /var/log/consul
consul_logfile: "{{ consul_logdir }}/consul.log"
consul_loglevel: INFO

consul_domain: consul
consul_datacenter: main
consul_interface: "
"
consul_ip: "{{ inventory_hostname }}"
consul_http_port: 8500
consul_dns_port: 8600

consul_configuration_template_path: consul.json.j2
consul_logrotate_template_path: logrotate.j2
consul_service_template_path: consul.service.j2

# ACLs #
consul_acl: true
consul_acl_datacenter: "{{ consul_datacenter }}"
consul_acl_default_policy: allow
consul_acl_down_policy: extend-cache
## Recommended to generate these values with uuidgen
consul_acl_master_token: master
consul_acl_agent_token: agent

## ACL for discovery synchronization between servers
# Example
# consul_acl_configuration_list:
  # Agent:
  #   token_type: client
  #   token: "{{ consul_acl_agent_token }}"
  #   rules:
  #     - node: ""
  #       policy: write
  #     - service: ""
  #       policy: read
