# Add each host to the [production] group and to a "type" group such as [web] or [db].
# List each machine only once per [group], even if it will host multiple sites.
all:
  vars:
    ansible_connection: ssh
web: 
  hosts:
    52.176.92.50:
  vars:
    ansible_ssh_user: striker
    ansible_ssh_pass: amit@17031993