# Add each host to the [production] group and to a "type" group such as [web] or [db].
# List each machine only once per [group], even if it will host multiple sites.
all:
  vars:
    ansible_connection: ssh
    netdata_uuid: '2c288770-9fa7-11e8-9a86-ab3f9df0a5a8'
    netdata_master_ip: '139.59.50.202' # Netdata floating IP
    deny_default_user: 'ubuntu'
    prod_consul_datacenter: 'do-blr'
    prod_consul_domain: 'charcoaleats'
    consul_server_ip: '159.89.163.216' # Consul Private IP
    redis_password: 473d67d08db4314ef0366d2504e37e9f44168abe
    redis_deepstream_port: 6363
    redis_deepstream_server: '13.232.230.45'
    deepstream_websocket_port: 5757
    deepstream_websocket_port_lb: 443
    deepstream_http_port: 8787
    pm2_user: root
    nodejs_application_port: 8888
    node_application_user: scylla
    deepstream_auth_url: http://preprod.charcoaleats.com/dashboard/open/live/authenticateUser
    git_host: gitlab.charcoalbiryani.com
    nodejs_install_npm_user: root
    env_host_name: preprod.charcoaleats.com
    nodejs_cpo_port: 8001
    nodejs_api_port: 8888
    admin_user: dranzer
    users:
      - name: "dranzer" # Ansible User
        groups:
          - sudo
        keys:
          - "{{ lookup('file', '/Users/amitverma/Projects/side-projects/galactus/pub_keys/dranzer.pub') }}"
      - name: "cerberus" # Admin User 
        groups:
          - sudo
        keys:
          - "{{ lookup('file', '/Users/amitverma/Projects/side-projects/galactus/pub_keys/cerberus.pub') }}"
      - name: "scylla" # Deploy User
        groups:
          - www
        keys:
          - "{{ lookup('file', '/Users/amitverma/Projects/side-projects/galactus/pub_keys/scylla.pub') }}"


consul_server:
  hosts:
    159.89.163.216:
  vars:
    ansible_ssh_user: root
    server_name: 'consul-sd'
    netdata_mode: 'slave'
    netdata_monitor_application: ['nginx']
    consul_mode: 'server'
    firewall_open_ports: [80,8300,8301,8500,8600,19999]
    nginx_custom_vhost: consul

netdata_server:
  hosts:
    159.65.152.64:
  vars:
    ansible_ssh_user: root
    server_name: 'netdata-server'
    netdata_mode: 'master'
    netdata_monitor_application: ['nginx']
    consul_mode: 'client'
    firewall_open_ports: [80,8300,8301,19999]
    nginx_custom_vhost: netdata

redis_msg_bus:
  hosts:
    13.232.230.45:
      consul_ip: '172.31.17.8'
  vars:
    ansible_ssh_user: dranzer
    server_name: 'redis-msg-bus'
    netdata_mode: 'slave'
    netdata_monitor_application: ['redis']
    consul_mode: 'client'
    firewall_open_ports: [8300,8301,19999,6363]
    nginx_custom_vhost: netdata
    redis_port: '{{ redis_deepstream_port }}'
    monitor_application_name: 'redis_msg_bus'
    health_check_script_enabled: true

deepstream_server:
  hosts:
    13.232.160.237:
        server_name: 'deepstream-node-1'
        consul_ip: '172.31.22.244'
    13.126.180.86:
        server_name: 'deepstream-node-2'
        consul_ip: '172.31.1.7'
  vars:
    ansible_ssh_user: dranzer
    netdata_mode: 'slave'
    netdata_monitor_application: []
    consul_mode: 'client'
    firewall_open_ports: [5757,8300,8301,19999,6363]
    is_redis_msg_plugin_used: true
    monitor_application_name: 'deepstream'
    deepstream_auth_enable: true
    health_check_script_enabled: true

deepstream_haproxy_lb:
  hosts:
    13.232.122.32:
        consul_ip: '172.31.22.29'
  vars:
    ansible_ssh_user: ubuntu
    server_name: 'deepstream-loadbalancer'
    netdata_mode: 'slave'
    netdata_monitor_application: ['haproxy']
    consul_mode: 'client'
    firewall_open_ports: [443,8300,8301,19999,5757]
    haproxy_custom_vhost: deepstream
    deepstream_server:
      - name: 'deepstream_s1'
        host: '13.232.160.237'
      - name: 'deepstream_s2'
        host: '13.126.180.86'
    haproxy_ssl_enable: true
    monitor_application_name: 'haproxy'
    health_check_script_enabled: true

nodejs_server:
  hosts:
    35.154.42.33:
      server_name: 'application-server-1'
      consul_ip: '172.31.30.230'
    13.232.108.119:
      server_name: 'application-server-2'
      consul_ip: '172.31.27.168'
    13.232.125.183:
      server_name: 'worker-server'
      consul_ip: '172.31.24.177'
    13.232.130.25:
      server_name: 'application-server-4'
      consul_ip: '172.31.4.148'
  vars:
    ansible_ssh_user: ubuntu
    netdata_mode: 'slave'
    netdata_monitor_application: ['nodejs']
    consul_mode: 'client'
    firewall_open_ports: [8888,8300,8301,19999]
    monitor_application_name: 'nodejs'
    health_check_script_enabled: true
