# Add each host to the [production] group and to a "type" group such as [web] or [db].
# List each machine only once per [group], even if it will host multiple sites.
all:
  vars:
    ansible_connection: ssh
web: 
  hosts:
    40.113.236.133:
  vars:
    ansible_ssh_user: server2
    ansible_ssh_pass: amit@17031993