# Add each host to the [production] group and to a "type" group such as [web] or [db].
# List each machine only once per [group], even if it will host multiple sites.
all:
  vars:
    ansible_connection: ssh
    netdata_uuid: '2c288770-9fa7-11e8-9a86-ab3f9df0a5a8'
    netdata_master_ip: '139.59.50.202' # Netdata floating IP
    deny_default_user: 'ubuntu'
    prod_consul_datacenter: 'DO-BLR'
    prod_consul_domain: 'charcoaleats'
    consul_server_ip: '159.89.163.216' # Consul Private IP
    #nodejs_install_npm_user: scylla
web: 
  hosts:
    206.189.131.39:
  vars:
    ansible_ssh_user: root
    server_name: 'tmp'
    netdata_mode: 'slave'
    netdata_monitor_application: ['nginx']

consul_server:
  hosts:
    159.89.163.216:
  vars:
    ansible_ssh_user: root
    server_name: 'consul-sd'
    netdata_mode: 'slave'
    netdata_monitor_application: ['nginx']
    consul_mode: 'server'
    firewall_open_ports: [80,8300,8301,8500,8600,19999]
    nginx_custom_vhost: consul

netdata_server:
  hosts:
    159.65.152.64:
  vars:
    ansible_ssh_user: root
    server_name: 'netdata-server'
    netdata_mode: 'master'
    netdata_monitor_application: ['nginx']
    consul_mode: 'client'
    firewall_open_ports: [80,8300,8301,19999]
    nginx_custom_vhost: netdata

nodejs_server:
  hosts:
    139.59.78.87:
  vars:
    ansible_ssh_user: root
    server_name: 'netdata-server'
    netdata_mode: 'master'
    netdata_monitor_application: ['nginx']
    consul_mode: 'client'
    firewall_open_ports: [80,8300,8301,19999]
    nginx_custom_vhost: netdata



#consul_client:
#  hosts:
#    178.128.72.107:
#  vars:
#    ansible_ssh_user: root
#    server_name: 'netdata-server'
#    netdata_mode: 'slave'
#    netdata_monitor_application: ['nginx']
#    consul_mode: 'client'

