---
- name: Ensure HAProxy is installed.
  package: name=haproxy state=present

- name: Ensure HAProxy is enabled (so init script will start it on Debian).
  lineinfile:
    dest: /etc/default/haproxy
    regexp: "^ENABLED.+$"
    line: "ENABLED=1"
    state: present
  when: ansible_os_family == 'Debian'

- name: Get HAProxy version.
  command: haproxy -v
  register: haproxy_version_result
  changed_when: false
  check_mode: no

- name: Set HAProxy version.
  set_fact:
    haproxy_version: "{{ '1.5' if '1.5.' in haproxy_version_result.stdout else '1.4' }}"

- name: Copy ssl file pem to server
  copy:
    src: "../../../../pub_keys/charcoaleats.pem"
    dest: /etc/ssl/charcoaleats.pem
    mode: 0400
  when: haproxy_ssl_enable


- name: Copy HAProxy configuration in place.
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  when: haproxy_custom_vhost is not defined
  notify: restart haproxy

- name: Copy Custom HAProxy configuration in place.
  template:
    src: "{{ haproxy_custom_vhost }}_haproxy.cfg.j2"
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  when: haproxy_custom_vhost is defined
  notify: restart haproxy


- name: Ensure HAProxy is started and enabled on boot.
  service: name=haproxy state=started enabled=yes
