---

- name: Consul | Check Consul version
  command: consul --version
  changed_when: false
  ignore_errors: true
  register: consul_installed_version
  check_mode: no

- name: Consul | Set consul_installed_version fact
  set_fact:
    consul_installed_version: "{{ consul_installed_version }}"

- name: Install - Set Consul hosts
  set_fact:
    consul_server_nodes: "{{ hostvars[groups['consul_server'][0]].cluster_private_ips  }}"
  when: groups.consul_server is defined
