---
- name: Check if MySQL is already installed.
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Update apt cache if MySQL is not yet installed.
  apt: update_cache=yes
  when: mysql_installed.stat.exists == false

- name: Determine required MySQL Python libraries.
  set_fact:
    deb_mysql_python_package: "{% if 'python3' in ansible_python_interpreter|default('') %}python3-mysqldb{% else %}python-mysqldb{% endif %}"

- name: Ensure MySQL Python libraries are installed.
  apt: "name={{ deb_mysql_python_package }} state=present"

- name: Ensure upstream MySQL repositories installed
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: mysql
  with_items:
    - "deb http://repo.mysql.com/apt/ubuntu/ xenial mysql-apt-config"
    - "deb http://repo.mysql.com/apt/ubuntu/ xenial mysql-5.7"
    - "deb http://repo.mysql.com/apt/ubuntu/ xenial mysql-tools"
    - "deb-src http://repo.mysql.com/apt/ubuntu/ xenial mysql-5.7"
  when: mysql_group_replication

- name: Ensure upstream MySQL repository GPG key installed
  apt_key:
    keyserver: pool.sks-keyservers.net
    id: A4A9406876FCBD3C456770C88C718D3B5072E1F5
    state: present
  when: mysql_group_replication

- name: Ensure MySQL packages are installed.
  apt: "name={{ mysql_packages }} state=present force=yes"
  register: deb_mysql_install_packages

# Because Ubuntu starts MySQL as part of the install process, we need to stop
# mysql and remove the logfiles in case the user set a custom log file size.
- name: Ensure MySQL is stopped after initial install.
  service: "name={{ mysql_daemon }} state=stopped"
  when: mysql_installed.stat.exists == false

- name: Delete innodb log files created by apt package after initial install.
  file: path={{ mysql_datadir }}/{{item}} state=absent
  with_items:
    - "ib_logfile0"
    - "ib_logfile1"
  when: mysql_installed.stat.exists == false
