---
- name: Gather variables for monit setup type
  include_vars: "{{ item }}"
  with_items: "{{ monitor_application_name | lower }}.yml"
  when: monitor_application_name is defined
  tags:
    - always

- include: debian/pkg.yml
  tags: monit_pkg
  when: ansible_os_family == "Debian"

- include: redhat/pkg.yml
  tags: monit_pkg
  when: ansible_os_family == "RedHat"

- include: config.yml
  tags: monit_config

- include: monitors.yml
  tags: monit_monitors
