---

- name: Add fail2ban plugins in netdata
  copy:
    src: plugins/fail2ban.conf
    dest: /etc/netdata/python.d/fail2ban.conf
    owner: netdata
    group: netdata
    mode: 0644
  when: "'fail2ban' in netdata_monitor_application"

- name: Add fail2ban charts in netdata
  copy:
    src: charts/fail2ban.chart.py
    dest: /etc/netdata/python.d/fail2ban.chart.py
    owner: netdata
    group: netdata
    mode: 0644
  when: "'fail2ban' in netdata_monitor_application"

- name: Add Monit plugin in netdata
  template:
    src: plugins/monit.conf.j2
    dest: /etc/netdata/python.d/monit.conf
    mode: 0644
  when: "'monit' in netdata_monitor_application"
  notify: restart netdata

- name: Add Monit charts in netdata
  copy:
    src: charts/monit.chart.py
    dest: /etc/netdata/python.d/monit.chart.py
    owner: netdata
    group: netdata
    mode: 0644
  when: "'monit' in netdata_monitor_application"


- name: Add ntpd plugins in netdata
  copy:
    src: plugins/ntpd.conf
    dest: /etc/netdata/python.d/ntpd.conf
    owner: netdata
    group: netdata
    mode: 0644
  when: "'ntp' in netdata_monitor_application"

- name: Add ntpd charts in netdata
  copy:
    src: charts/ntpd.chart.py
    dest: /etc/netdata/python.d/ntpd.chart.py
    owner: netdata
    group: netdata
    mode: 0644
  when: "'ntp' in netdata_monitor_application"


- name: Add Mysql plugin in netdata
  template:
    src: plugins/mysql.conf.j2
    dest: /etc/netdata/python.d/mysql.conf
    mode: 0644
  when: "'mysql' in netdata_monitor_application"
  notify: restart netdata


- name: Add Mysql charts in netdata
  copy:
    src: charts/mysql.chart.py
    dest: /etc/netdata/python.d/mysql.chart.py
    owner: netdata
    group: netdata
    mode: 0644
  when: "'mysql' in netdata_monitor_application"

- name: Add Proxysql plugin in netdata
  template:
    src: plugins/proxysql.conf.j2
    dest: /etc/netdata/python.d/proxysql.conf
    mode: 0644
  when: "'proxysql' in netdata_monitor_application"
  notify: restart netdata

- name: Add Proxysql charts in netdata
  copy:
    src: charts/proxysql.chart.py
    dest: /etc/netdata/python.d/proxysql.chart.py
    owner: netdata
    group: netdata
    mode: 0644
  when: "'proxysql' in netdata_monitor_application"


- name: Add haproxy plugin in netdata
  template:
    src: plugins/haproxy.conf.j2
    dest: /etc/netdata/python.d/haproxy.conf
    mode: 0644
  when: "'haproxy' in netdata_monitor_application"
  notify: restart netdata

- name: Add haproxy charts in netdata
  copy:
    src: charts/haproxy.chart.py
    dest: /etc/netdata/python.d/haproxy.chart.py
    owner: netdata
    group: netdata
    mode: 0644
  when: "'haproxy' in netdata_monitor_application"


- name: Add Nginx plugin in netdata
  copy:
    src: plugins/nginx.conf
    dest: /etc/netdata/python.d/nginx.conf
    owner: netdata
    group: netdata
    mode: 0644
  when: "'nginx' in netdata_monitor_application"

- name: Add Nginx Monitoring in netdata
  blockinfile: 
    path: /etc/netdata/python.d/nginx.conf
    block: |
      job_name:                 # the JOB's name as it will appear at the
        name: nginx             # the JOB's data collection frequency 
        update_every: 1    
        priority: 60000         # the JOB's order on the dashboard
        retries: 60             # the JOB's number of restoration attempts
        autodetection_retry: 0  # the JOB's re-check interval in seconds
  when: "'nginx' in netdata_monitor_application"
  notify: restart netdata


- name: Add redis plugin in netdata
  copy:
    src: plugins/redis.conf
    dest: /etc/netdata/python.d/redis.conf
    owner: netdata
    group: netdata
    mode: 0644
  when: "'redis' in netdata_monitor_application"

- name: Add Redis Monitoring in netdata
  blockinfile: 
    path: /etc/netdata/python.d/redis.conf
    block: |
      job_name:
          name: redis           # the JOB's name as it will appear at the
          update_every: 1         # the JOB's data collection frequency
          priority: 60000         # the JOB's order on the dashboard
          retries: 60             # the JOB's number of restoration attempts
          autodetection_retry: 0  # the JOB's re-check interval in seconds
      socket:
        name     : 'local'
        socket   : '/var/lib/redis/redis.sock'

      localhost:
        name     : 'local'
        host     : 'localhost'
        port     : '{{ redis_deepstream_port }}'
        pass     : '{{ redis_password }}'
  when: "'redis' in netdata_monitor_application"
  notify: restart netdata