---

- name: Add Monit plugin in netdata
  copy:
    src: plugins/monit.conf
    dest: /etc/netdata/python.d/monit.conf
    owner: netdata
    group: netdata
    mode: 0644
  when: "'monit' in netdata_monitor_application"

- name: Add NTP plugin in netdata
  copy:
    src: plugins/ntpd.conf
    dest: /etc/netdata/python.d/ntpd.conf
    owner: netdata
    group: netdata
    mode: 0644
  when: "'ntp' in netdata_monitor_application"

- name: Add Nginx plugin in netdata
  copy:
    src: plugins/nginx.conf
    dest: /etc/netdata/python.d/nginx.conf
    owner: netdata
    group: netdata
    mode: 0644
  when: "'nginx' in netdata_monitor_application"

- name: Add Nginx Monitoring in netdata
  blockinfile: 
    path: /etc/netdata/python.d/nginx.conf
    block: |
      job_name:                 # the JOB's name as it will appear at the
        name: nginx             # the JOB's data collection frequency 
        update_every: 1    
        priority: 60000         # the JOB's order on the dashboard
        retries: 60             # the JOB's number of restoration attempts
        autodetection_retry: 0  # the JOB's re-check interval in seconds
  when: "'nginx' in netdata_monitor_application"
  notify: restart netdata

- name: Add HaProxy plugin in netdata
  copy:
    src: plugins/haproxy.conf
    dest: /etc/netdata/python.d/haproxy.conf
    owner: netdata
    group: netdata
    mode: 0644
  when: "'haproxy' in netdata_monitor_application"

- name: Add Haproxy Monitoring in netdata
  blockinfile: 
    path: /etc/netdata/python.d/haproxy.conf
    block: |
      job_name:
          name: haproxy           
          update_every: 1         
          priority: 60000         
          retries: 60             
          autodetection_retry: 0  
      via_url:
          user : '{{ haproxy_stat_auth_user }}'
          pass : '{{ haproxy_stat_auth_pwd }}'
          url : 'http://127.0.0.1:18999/haproxy_stats;csv;norefresh'

  when: "'haproxy' in netdata_monitor_application"
  notify: restart netdata

- name: Add redis plugin in netdata
  copy:
    src: plugins/redis.conf
    dest: /etc/netdata/python.d/redis.conf
    owner: netdata
    group: netdata
    mode: 0644
  when: "'redis' in netdata_monitor_application"

- name: Add Redis Monitoring in netdata
  blockinfile: 
    path: /etc/netdata/python.d/redis.conf
    block: |
      job_name:
          name: redis           # the JOB's name as it will appear at the
          update_every: 1         # the JOB's data collection frequency
          priority: 60000         # the JOB's order on the dashboard
          retries: 60             # the JOB's number of restoration attempts
          autodetection_retry: 0  # the JOB's re-check interval in seconds
      socket:
        name     : 'local'
        socket   : '/var/lib/redis/redis.sock'

      localhost:
        name     : 'local'
        host     : 'localhost'
        port     : '{{ redis_deepstream_port }}'
        pass     : '{{ redis_password }}'
  when: "'redis' in netdata_monitor_application"
  notify: restart netdata