- name: Replace netdata config for slave
  template:
    src: "slave/netdata.d.j2"
    dest: /etc/netdata/netdata.conf
    mode: 0644

- name: Replace netdata health alarm config for slave
  template:
    src: "master/health_alarm_notify.conf.j2"
    dest: /etc/netdata/health_alarm_notify.conf
    mode: 0644
  when: is_netdata_alarm_enable
  notify: restart netdata

- name: Disable change subject
  lineinfile:
    dest: /usr/libexec/netdata/plugins.d/alarm-notify.sh
    regexp: '^Subject: ${host} ${status_message} - ${name//_/ } - ${chart}'
    line: 'Subject: {{ server_name }} ${status_message} - ${name//_/ } - ${chart}'
    backrefs: true
  when: is_netdata_alarm_enable
  notify: restart netdata

- name: Replace netdata stream config for slave
  template:
    src: "slave/stream.d.j2"
    dest: /etc/netdata/stream.conf
    mode: 0644
  notify: restart netdata
