---
- name: Create teleport service (upstart).
  template:
    src: "teleport.upstart.j2"
    dest: "/etc/init/teleport.conf"
    owner: "root"
    group: "root"
    mode: 0644
  register: service_installed

- name: initctl reload-configuration
  shell: initctl reload-configuration
  become: yes
  when: service_installed.changed