---
monit_services:
  - name: supervisor
    type: process
    target: /var/run/supervisord.pid
    start: /usr/sbin/service supervisor start
    stop: /usr/sbin/service supervisor stop
    restart: /usr/sbin/service supervisor restart
    rules:
      - "if 5 restarts within 5 cycles then timeout"
  - name: deepstream
    type: process_by_name
    target: deepstream
    start: /usr/bin/supervisorctl start deepstream_daemon
    stop: /usr/bin/supervisorctl stop deepstream_daemon
    restart: /usr/bin/supervisorctl restart deepstream_daemon
    rules:
      - "if failed port 5757 protocol http then restart"
      - "if 5 restarts within 5 cycles then timeout"
  - name: netdata
    type: process
    target: /var/run/netdata/netdata.pid
    start: /usr/sbin/service netdata start 
    stop: /usr/sbin/service netdata stop 
    restart: /usr/sbin/service netdata restart 
    rules:
      - "if 5 restarts within 5 cycles then timeout"
  - name: consul
    type: process_by_name
    target: consul
    start: /usr/sbin/service consul start 
    stop: /usr/sbin/service consul stop 
    restart: /usr/sbin/service consul restart 
    rules:
      - "if failed port 8500 protocol http then restart"
      - "if 5 restarts within 5 cycles then timeout"
