---
monit_services:
  - name: deepstream
    type: process_by_name
    target: deepstream
    start: /usr/bin/supervisorctl start deepstream_daemon
    stop: /usr/bin/supervisorctl stop deepstream_daemon
    restart: /usr/bin/supervisorctl restart deepstream_daemon
    rules:
      - "if failed port 5757 then restart"
      - "if 5 restarts within 5 cycles then timeout"
