---
monit_services:
  - name: netdata
    type: process
    target: /var/run/netdata/netdata.pid
    start: /usr/sbin/service netdata start 
    stop: /usr/sbin/service netdata stop 
    restart: /usr/sbin/service netdata restart 
    rules:
        - "if failed port 19999 then restart"
        - "if 5 restarts within 5 cycles then timeout"