---
monit_services:
  - name: nginx
    type: process_by_name
    target: nginx
    start: /usr/sbin/service nginx start 
    stop: /usr/sbin/service nginx stop 
    restart: /usr/sbin/service nginx restart 
    rules:
      - "if failed port 443 protocol http then restart"
      - "if 5 restarts within 5 cycles then timeout"