---
monit_services:
  - name: pm2
    type: process_by_name
    target: pm2
    start: /usr/sbin/service pm2 start 
    stop: /usr/sbin/service pm2 stop 
    restart: /usr/bin/service pm2 restart 
    rules:
      - "if failed port 8888 protocol http then restart"
      - "if 5 restarts within 5 cycles then timeout"