---
monit_services:
  - name: pm2
    type: process_by_name
    target: pm2
    start: /usr/sbin/service pm2 start 
    stop: /usr/sbin/service pm2 stop 
    restart: /usr/bin/service pm2 restart 
    rules:
      - "if failed port {{ nodejs_application_port }} protocol http then restart"
      - "if 5 restarts within 5 cycles then timeout"
  - name: netdata
    type: process
    target: /var/run/netdata/netdata.pid
    start: /usr/sbin/service netdata start 
    stop: /usr/sbin/service netdata stop 
    restart: /usr/sbin/service netdata restart 
    rules:
      - "if 5 restarts within 5 cycles then timeout"
  - name: consul
    type: process_by_name
    target: consul
    start: /usr/sbin/service consul start 
    stop: /usr/sbin/service consul stop 
    restart: /usr/sbin/service consul restart 
    rules:
      - "if failed port 8500 protocol http then restart"
      - "if 5 restarts within 5 cycles then timeout"
