---
monit_services:
  - name: proxysql
    type: process_by_name
    target: proxysql
    start: /usr/sbin/service proxysql start 
    stop: /usr/sbin/service proxysql stop 
    restart: /usr/sbin/service proxysql restart 
    rules:
      - "if failed host 127.0.0.1 port 6032 then restart"
      - "if 5 restarts within 5 cycles then timeout"
  - name: netdata
    type: process_by_name
    target: netdata
    start: /usr/sbin/service netdata start 
    stop: /usr/sbin/service netdata stop 
    restart: /usr/sbin/service netdata restart 
    rules:
      - "if failed port 18999 protocol http then restart"
      - "if 5 restarts within 5 cycles then timeout"

