---
monit_services:
  - name: redis
    type: process_by_name
    target: redis
    start: /usr/bin/service redis start 
    stop: /usr/bin/service redis stop 
    restart: /usr/bin/service redis restart 
    rules:
      - "if failed port {{ redis_deepstream_port }} protocol http then restart"
      - "if 5 restarts within 5 cycles then timeout"
  - name: netdata
    type: process
    target: /var/run/netdata/netdata.pid
    start: /usr/sbin/service netdata start 
    stop: /usr/sbin/service netdata stop 
    restart: /usr/sbin/service netdata restart 
    rules:
      - "if 5 restarts within 5 cycles then timeout"
  - name: consul
    type: process_by_name
    target: consul
    start: /usr/sbin/service consul start 
    stop: /usr/sbin/service consul stop 
    restart: /usr/sbin/service consul restart 
    rules:
      - "if failed port 8500 protocol http then restart"
      - "if 5 restarts within 5 cycles then timeout"
