---
monit_services:
  - name: vault
    type: process_by_name
    target: vault
    start: /usr/sbin/service consul start 
    stop: /usr/sbin/service consul stop 
    restart: /usr/sbin/service consul restart 
    rules:
      - "if failed port 8200 protocol http then restart"
      - "if 5 restarts within 5 cycles then timeout"
