---
- name : Set rmem_max
  sysctl:
    name: net.core.rmem_max
    value: 134217728
    sysctl_set: yes
    state: present
    reload: yes

- name : Set wmem_max
  sysctl:
    name: net.core.wmem_max
    value: 134217728
    sysctl_set: yes
    state: present
    reload: yes

- name : Set rmem_default
  sysctl:
    name: net.core.rmem_default
    value: 16777216
    sysctl_set: yes
    state: present
    reload: yes

- name : Set wmem_default
  sysctl:
    name: net.core.wmem_default
    value: 16777216
    sysctl_set: yes
    state: present
    reload: yes

- name : Set optmem_max 
  sysctl:
    name: net.core.optmem_max
    value: 40960
    sysctl_set: yes
    state: present
    reload: yes

- name : Set tcp_rmem
  sysctl:
    name: net.ipv4.tcp_rmem
    value: "4096 87380 134217728"
    sysctl_set: yes
    state: present
    reload: yes

- name : Set tcp_wmem
  sysctl:
    name: net.ipv4.tcp_wmem
    value: "4096 87380 134217728"
    sysctl_set: yes
    state: present
    reload: yes

- name : Set tcp_moderate_rcvbuf
  sysctl:
    name: net.ipv4.tcp_moderate_rcvbuf
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name : Set tcp_no_metrics_save 
  sysctl:
    name: net.ipv4.tcp_no_metrics_save
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name : Set netdev_budget 
  sysctl:
    name: net.core.netdev_budget
    value: 60000
    sysctl_set: yes
    state: present
    reload: yes

- name : Set tcp_congestion_control 
  sysctl:
    name: net.ipv4.tcp_congestion_control
    value: "htcp"
    sysctl_set: yes
    state: present
    reload: yes

- name : Set tcp_max_syn_backlog
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: 30000
    sysctl_set: yes
    state: present
    reload: yes

- name : Set tcp_max_tw_buckets 
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 2000000
    sysctl_set: yes
    state: present
    reload: yes

- name : Set tcp_tw_reuse
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    sysctl_set: yes
    state: present
    reload: yes   

- name : Set tcp_slow_start_after_idle 
  sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: 0
    sysctl_set: yes
    state: present
    reload: yes   

- name : Set udp_rmem_min 
  sysctl:
    name: net.ipv4.udp_rmem_min
    value: 8192
    sysctl_set: yes
    state: present
    reload: yes   

- name : Set udp_wmem_min
  sysctl:
    name: net.ipv4.udp_wmem_min
    value: 8192
    sysctl_set: yes
    state: present
    reload: yes   

- name : Set netdev_budget_usecs
  sysctl:
    name: net.core.netdev_budget_usecs
    value: 6000
    sysctl_set: yes
    state: present
    reload: yes   

- name : Set somaxconn
  sysctl:
    name: net.core.somaxconn
    value: 32768
    sysctl_set: yes
    state: present
    reload: yes   

- name : Set ip_local_port_range
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: "4000 65000"
    sysctl_set: yes
    state: present
    reload: yes   

- name : Set tcp_fin_timeout
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 5
    sysctl_set: yes
    state: present
    reload: yes   

- name : Set file-max
  sysctl:
    name: fs.file-max
    value: 10000000
    sysctl_set: yes
    state: present
    reload: yes   

- name : Set nr_open
  sysctl:
    name: fs.nr_open
    value: 10000000
    sysctl_set: yes
    state: present
    reload: yes   

- name : Set tcp_mtu_probing 
  sysctl:
    name: net.ipv4.tcp_mtu_probing
    value: 1
    sysctl_set: yes
    state: present
    reload: yes   

- name : Set tcp_timestamps 
  sysctl:
    name: net.ipv4.tcp_timestamps
    value: 0
    sysctl_set: yes
    state: present
    reload: yes   

- name : Set tcp_sack 
  sysctl:
    name: net.ipv4.tcp_sack
    value: 0
    sysctl_set: yes
    state: present
    reload: yes   

- name : Set tcp_syncookies 
  sysctl:
    name: net.ipv4.tcp_syncookies
    value: 0
    sysctl_set: yes
    state: present
    reload: yes   

- name: configure system settings, file descriptors and number of threads
  pam_limits:
    domain: root
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
    - { limit_type: '-', limit_item: 'nofile', value: 25000 }
    - { limit_type: '-', limit_item: 'nproc', value: 25000 }
    - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
    - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }

# - name: Install increase ulimit
#   shell: "ulimit -n 25000"

- name: reload settings from all system configuration files
  shell: sysctl --system