---
- name: Disable empty password login
  lineinfile: dest={{ sshd_config }} regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"

- name: Disable remote root login
  lineinfile: dest={{ sshd_config }} regexp="^#?PermitRootLogin" line="PermitRootLogin no"

- name: Disable password login
  lineinfile: dest={{ sshd_config }} regexp="^#?PasswordAuthentication" line="PasswordAuthentication no"

- name: Enable PAM
  lineinfile: dest={{ sshd_config }} regexp="^#?UsePAM" line="UsePAM yes"

- name: restart ssh
  service:
    name: ssh
    state: restarted
