---

- name: Nodejs | Install pm2 package
  npm:
    name: pm2
    global: yes
    version: "{{ pm2_version | default(omit) }}"

- name:  Nodejs | Looking up user home
  shell: >
    egrep "^{{ pm2_user }}:" /etc/passwd | awk -F: '{ print $6 }'
  changed_when: false
  register: pm2_user_home

- name: Installing startup script
  command: "pm2 startup -u {{ pm2_user }} --hp {{ pm2_user_home.stdout }}"
