---
consul_services_register:
    - name: mysql
      tags: ['mysql']
      port: 3306
      script: "mysqladmin ping --host=localhost --port=3306 --user=root --password={{ mysql_root_password }}"
      interval: "60s"