---
- name: Install ProxySQL deb file
  apt:
    deb: "https://github.com/sysown/proxysql/releases/download/v{{ proxysql_version }}/proxysql_{{ proxysql_version }}-ubuntu16_amd64.deb"
    state: present
  become: true

- name: Download MySQL client
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  become: true
  with_items:
    - mysql-client
    - python-mysqldb
